import Head from "next/head";
import Image from "next/image";
import Selectr from "../components/selectRegion";
import Search from "../images/icons/search";

export default function Home() {
  return (
    <div className="min-h-screen flex justify-center">
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto">
        <div className="grid grid-cols-3">
          <div className="ml-80">
            <Selectr />
          </div>
          <div>
            <input
              className="bg-primary rounded-lg w-96 h-10 text-xl text-slate-50 p-4"
              type="search"
              name="search"
              id="search"
              placeholder="Search"
            ></input>
          </div>
          <div className="mt-0.5">
            <button
              type="submit"
              className="bg-blue-500 hover:bg-blue-700 px-1 py-1 text-white font-bold  rounded"
            >
              <Search width={50} height={30} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
