import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="bg-red-600">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Gaming</p>
    </div>
  );
}
