import Head from "next/head";
import Image from "next/image";
import Selectr from "../components/selectRegion";
import UserSearch from "../components/userSearch";

export default function Home() {
  return (
    <div className="min-h-screen flex justify-center">
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid items-center ">
        <UserSearch
          className={"flex flex-row"}
          selectRegion={""}
          searchButtonOuter={"mt-0.5"}
          inputInder={
            "bg-primary rounded-lg w-96 h-10 text-xl text-slate-50 p-4"
          }
          searchButtonInder={
            "bg-blue-500 hover:bg-blue-700 px-1 py-1 text-white font-bold  rounded"
          }
        />
      </div>
    </div>
  );
}
