import Head from "next/head";
import Image from "next/image";

export default function Search() {
  return (
    <div className="bg-red-600">
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}