import Head from "next/head";
import Image from "next/image";

export default function Search() {
  return (
    <div className="min-h-screen flex  bg-secondary">
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto">
        <input
          className="bg-primary rounded-lg w-96 h-10 text-xl ml-0.5 text-slate-50 p-4"
          type="search"
          name="search"
          id="search"
          placeholder="Search"
        ></input>
        <button type="submit" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Search</button>
        </div>
    </div>
  );
}
